/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.formula.sablecc.parser;

import fr.umlv.symphonie.formula.sablecc.lexer.*;
import fr.umlv.symphonie.formula.sablecc.node.*;
import fr.umlv.symphonie.formula.sablecc.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected Node node;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_shift;
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    protected void filter() throws ParserException, LexerException, IOException
    {
    }

    public Parser(Lexer lexer)
    {
        this.lexer = lexer;

        if(actionTable == null)
        {
            try
            {
                DataInputStream s = new DataInputStream(
                    new BufferedInputStream(
                    Parser.class.getResourceAsStream("parser.dat")));

                // read actionTable
                int length = s.readInt();
                actionTable = new int[length][][];
                for(int i = 0; i < actionTable.length; i++)
                {
                    length = s.readInt();
                    actionTable[i] = new int[length][3];
                    for(int j = 0; j < actionTable[i].length; j++)
                    {
                        for(int k = 0; k < 3; k++)
                        {
                            actionTable[i][j][k] = s.readInt();
                        }
                    }
                }

                // read gotoTable
                length = s.readInt();
                gotoTable = new int[length][][];
                for(int i = 0; i < gotoTable.length; i++)
                {
                    length = s.readInt();
                    gotoTable[i] = new int[length][2];
                    for(int j = 0; j < gotoTable[i].length; j++)
                    {
                        for(int k = 0; k < 2; k++)
                        {
                            gotoTable[i][j][k] = s.readInt();
                        }
                    }
                }

                // read errorMessages
                length = s.readInt();
                errorMessages = new String[length];
                for(int i = 0; i < errorMessages.length; i++)
                {
                    length = s.readInt();
                    StringBuffer buffer = new StringBuffer();

                    for(int j = 0; j < length; j++)
                    {
                        buffer.append(s.readChar());
                    }
                    errorMessages[i] = buffer.toString();
                }

                // read errors
                length = s.readInt();
                errors = new int[length];
                for(int i = 0; i < errors.length; i++)
                {
                    errors[i] = s.readInt();
                }

                s.close();
            }
            catch(Exception e)
            {
                throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
            }
        }
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private void push(int state, Node node, boolean filter) throws ParserException, LexerException, IOException
    {
        this.node = node;

        if(filter)
        {
            filter();
        }

        if(!stack.hasNext())
        {
            stack.add(new State(state, this.node));
            return;
        }

        State s = (State) stack.next();
        s.state = state;
        s.node = this.node;
    }

    private int state()
    {
        State s = (State) stack.previous();
        stack.next();
        return s.state;
    }

    private Node pop()
    {
        return (Node) ((State) stack.previous()).node;
    }

    private int index(Switchable token)
    {
        converter.index = -1;
        token.apply(converter);
        return converter.index;
    }

    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, false);

        List ign = null;
        while(true)
        {
            while(index(lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new TypedLinkedList(NodeCast.instance);
                }

                ign.add(lexer.next());
            }

            if(ign != null)
            {
                ignoredTokens.setIn(lexer.peek(), ign);
                ign = null;
            }

            last_pos = lexer.peek().getPos();
            last_line = lexer.peek().getLine();
            last_token = lexer.peek();

            int index = index(lexer.peek());
            action[0] = actionTable[state()][0][1];
            action[1] = actionTable[state()][0][2];

            int low = 1;
            int high = actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    action[0] = actionTable[state()][middle][1];
                    action[1] = actionTable[state()][middle][2];
                    break;
                }
            }

            switch(action[0])
            {
                case SHIFT:
                    push(action[1], lexer.next(), true);
                    last_shift = action[1];
                    break;
                case REDUCE:
                    switch(action[1])
                    {
                    case 0: { Node node = new0(); push(goTo(0), node, true); } break;
                    case 1: { Node node = new1(); push(goTo(1), node, true); } break;
                    case 2: { Node node = new2(); push(goTo(1), node, true); } break;
                    case 3: { Node node = new3(); push(goTo(1), node, true); } break;
                    case 4: { Node node = new4(); push(goTo(2), node, true); } break;
                    case 5: { Node node = new5(); push(goTo(2), node, true); } break;
                    case 6: { Node node = new6(); push(goTo(2), node, true); } break;
                    case 7: { Node node = new7(); push(goTo(2), node, true); } break;
                    case 8: { Node node = new8(); push(goTo(2), node, true); } break;
                    case 9: { Node node = new9(); push(goTo(2), node, true); } break;
                    case 10: { Node node = new10(); push(goTo(2), node, true); } break;
                    case 11: { Node node = new11(); push(goTo(3), node, true); } break;
                    case 12: { Node node = new12(); push(goTo(3), node, true); } break;
                    case 13: { Node node = new13(); push(goTo(3), node, true); } break;
                    case 14: { Node node = new14(); push(goTo(4), node, true); } break;
                    case 15: { Node node = new15(); push(goTo(4), node, true); } break;
                    case 16: { Node node = new16(); push(goTo(4), node, true); } break;
                    case 17: { Node node = new17(); push(goTo(5), node, true); } break;
                    case 18: { Node node = new18(); push(goTo(5), node, true); } break;
                    case 19: { Node node = new19(); push(goTo(5), node, true); } break;
                    case 20: { Node node = new20(); push(goTo(5), node, true); } break;
                    case 21: { Node node = new21(); push(goTo(6), node, true); } break;
                    case 22: { Node node = new22(); push(goTo(6), node, true); } break;
                    case 23: { Node node = new23(); push(goTo(7), node, true); } break;
                    case 24: { Node node = new24(); push(goTo(7), node, true); } break;
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) lexer.next();
                        PFormule node1 = (PFormule) pop();
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(last_token,
                        "[" + last_line + "," + last_pos + "] " +
                        errorMessages[errors[action[1]]]);
            }
        }
    }

    Node new0()
    {
        PExpr node1 = (PExpr) pop();
        AExprFormule node = new AExprFormule(node1);
        return node;
    }

    Node new1()
    {
        PExprLowPriority node1 = (PExprLowPriority) pop();
        ALowPriorityExpr node = new ALowPriorityExpr(node1);
        return node;
    }

    Node new2()
    {
        PExprLowPriority node3 = (PExprLowPriority) pop();
        TAnd node2 = (TAnd) pop();
        PExpr node1 = (PExpr) pop();
        AAndExpr node = new AAndExpr(node1, node2, node3);
        return node;
    }

    Node new3()
    {
        PExprLowPriority node3 = (PExprLowPriority) pop();
        TOr node2 = (TOr) pop();
        PExpr node1 = (PExpr) pop();
        AOrExpr node = new AOrExpr(node1, node2, node3);
        return node;
    }

    Node new4()
    {
        PExprNormalPriority node1 = (PExprNormalPriority) pop();
        ANormalPriorityExprLowPriority node = new ANormalPriorityExprLowPriority(node1);
        return node;
    }

    Node new5()
    {
        PExprNormalPriority node3 = (PExprNormalPriority) pop();
        TLt node2 = (TLt) pop();
        PExprLowPriority node1 = (PExprLowPriority) pop();
        ALowerThanExprLowPriority node = new ALowerThanExprLowPriority(node1, node2, node3);
        return node;
    }

    Node new6()
    {
        PExprNormalPriority node3 = (PExprNormalPriority) pop();
        TLteq node2 = (TLteq) pop();
        PExprLowPriority node1 = (PExprLowPriority) pop();
        ALowerEqualExprLowPriority node = new ALowerEqualExprLowPriority(node1, node2, node3);
        return node;
    }

    Node new7()
    {
        PExprNormalPriority node3 = (PExprNormalPriority) pop();
        TGt node2 = (TGt) pop();
        PExprLowPriority node1 = (PExprLowPriority) pop();
        AGreaterThanExprLowPriority node = new AGreaterThanExprLowPriority(node1, node2, node3);
        return node;
    }

    Node new8()
    {
        PExprNormalPriority node3 = (PExprNormalPriority) pop();
        TGteq node2 = (TGteq) pop();
        PExprLowPriority node1 = (PExprLowPriority) pop();
        AGreaterEqExprLowPriority node = new AGreaterEqExprLowPriority(node1, node2, node3);
        return node;
    }

    Node new9()
    {
        PExprNormalPriority node3 = (PExprNormalPriority) pop();
        TEqual node2 = (TEqual) pop();
        PExprLowPriority node1 = (PExprLowPriority) pop();
        AEqualExprLowPriority node = new AEqualExprLowPriority(node1, node2, node3);
        return node;
    }

    Node new10()
    {
        PExprNormalPriority node3 = (PExprNormalPriority) pop();
        TNeq node2 = (TNeq) pop();
        PExprLowPriority node1 = (PExprLowPriority) pop();
        ANotEqualExprLowPriority node = new ANotEqualExprLowPriority(node1, node2, node3);
        return node;
    }

    Node new11()
    {
        PExprHighPriority node1 = (PExprHighPriority) pop();
        AHighPriorityExprNormalPriority node = new AHighPriorityExprNormalPriority(node1);
        return node;
    }

    Node new12()
    {
        PExprHighPriority node3 = (PExprHighPriority) pop();
        TPlus node2 = (TPlus) pop();
        PExprNormalPriority node1 = (PExprNormalPriority) pop();
        APlusExprNormalPriority node = new APlusExprNormalPriority(node1, node2, node3);
        return node;
    }

    Node new13()
    {
        PExprHighPriority node3 = (PExprHighPriority) pop();
        TMinus node2 = (TMinus) pop();
        PExprNormalPriority node1 = (PExprNormalPriority) pop();
        AMinusExprNormalPriority node = new AMinusExprNormalPriority(node1, node2, node3);
        return node;
    }

    Node new14()
    {
        PExpratom node1 = (PExpratom) pop();
        AExpratomExprHighPriority node = new AExpratomExprHighPriority(node1);
        return node;
    }

    Node new15()
    {
        PExpratom node3 = (PExpratom) pop();
        TMult node2 = (TMult) pop();
        PExprHighPriority node1 = (PExprHighPriority) pop();
        AMultExprHighPriority node = new AMultExprHighPriority(node1, node2, node3);
        return node;
    }

    Node new16()
    {
        PExpratom node3 = (PExpratom) pop();
        TDiv node2 = (TDiv) pop();
        PExprHighPriority node1 = (PExprHighPriority) pop();
        ADivExprHighPriority node = new ADivExprHighPriority(node1, node2, node3);
        return node;
    }

    Node new17()
    {
        TRPar node4 = (TRPar) pop();
        PBloc node3 = (PBloc) pop();
        TLPar node2 = (TLPar) pop();
        TFunctionKeyName node1 = (TFunctionKeyName) pop();
        APluginsFunctionExpratom node = new APluginsFunctionExpratom(node1, node2, node3, node4);
        return node;
    }

    Node new18()
    {
        TIconst node1 = (TIconst) pop();
        AIconstExpratom node = new AIconstExpratom(node1);
        return node;
    }

    Node new19()
    {
        TDconst node1 = (TDconst) pop();
        ADconstExpratom node = new ADconstExpratom(node1);
        return node;
    }

    Node new20()
    {
        TRBrace node4 = (TRBrace) pop();
        TName node3 = (TName) pop();
        TLBrace node2 = (TLBrace) pop();
        TDollar node1 = (TDollar) pop();
        AColumnExpratom node = new AColumnExpratom(node1, node2, node3, node4);
        return node;
    }

    Node new21()
    {
        TFunctionKeyName node2 = (TFunctionKeyName) pop();
        TDollar node1 = (TDollar) pop();
        APluginsKeyWordsBloc node = new APluginsKeyWordsBloc(node1, node2);
        return node;
    }

    Node new22()
    {
        TRBrace node4 = (TRBrace) pop();
        PCourses node3 = (PCourses) pop();
        TLBrace node2 = (TLBrace) pop();
        TDollar node1 = (TDollar) pop();
        ACellAccessBloc node = new ACellAccessBloc(node1, node2, node3, node4);
        return node;
    }

    Node new23()
    {
        TName node1 = (TName) pop();
        ASingleCourses node = new ASingleCourses(node1);
        return node;
    }

    Node new24()
    {
        PCourses node3 = (PCourses) pop();
        TComma node2 = (TComma) pop();
        TName node1 = (TName) pop();
        AMultipleCourses node = new AMultipleCourses(node1, node2, node3);
        return node;
    }

    private static int[][][] actionTable;
/*      {
			{{-1, ERROR, 0}, {14, SHIFT, 1}, {15, SHIFT, 2}, {16, SHIFT, 3}, {17, SHIFT, 4}, },
			{{-1, ERROR, 1}, {18, SHIFT, 11}, },
			{{-1, REDUCE, 18}, },
			{{-1, REDUCE, 19}, },
			{{-1, ERROR, 4}, {12, SHIFT, 12}, },
			{{-1, ERROR, 5}, {22, ACCEPT, -1}, },
			{{-1, REDUCE, 0}, {0, SHIFT, 13}, {1, SHIFT, 14}, },
			{{-1, REDUCE, 1}, {2, SHIFT, 15}, {3, SHIFT, 16}, {4, SHIFT, 17}, {5, SHIFT, 18}, {6, SHIFT, 19}, {7, SHIFT, 20}, },
			{{-1, REDUCE, 4}, {8, SHIFT, 21}, {9, SHIFT, 22}, },
			{{-1, REDUCE, 11}, {10, SHIFT, 23}, {11, SHIFT, 24}, },
			{{-1, REDUCE, 14}, },
			{{-1, ERROR, 11}, {19, SHIFT, 25}, },
			{{-1, ERROR, 12}, {14, SHIFT, 26}, },
			{{-1, ERROR, 13}, {14, SHIFT, 1}, {15, SHIFT, 2}, {16, SHIFT, 3}, {17, SHIFT, 4}, },
			{{-1, ERROR, 14}, {14, SHIFT, 1}, {15, SHIFT, 2}, {16, SHIFT, 3}, {17, SHIFT, 4}, },
			{{-1, ERROR, 15}, {14, SHIFT, 1}, {15, SHIFT, 2}, {16, SHIFT, 3}, {17, SHIFT, 4}, },
			{{-1, ERROR, 16}, {14, SHIFT, 1}, {15, SHIFT, 2}, {16, SHIFT, 3}, {17, SHIFT, 4}, },
			{{-1, ERROR, 17}, {14, SHIFT, 1}, {15, SHIFT, 2}, {16, SHIFT, 3}, {17, SHIFT, 4}, },
			{{-1, ERROR, 18}, {14, SHIFT, 1}, {15, SHIFT, 2}, {16, SHIFT, 3}, {17, SHIFT, 4}, },
			{{-1, ERROR, 19}, {14, SHIFT, 1}, {15, SHIFT, 2}, {16, SHIFT, 3}, {17, SHIFT, 4}, },
			{{-1, ERROR, 20}, {14, SHIFT, 1}, {15, SHIFT, 2}, {16, SHIFT, 3}, {17, SHIFT, 4}, },
			{{-1, ERROR, 21}, {14, SHIFT, 1}, {15, SHIFT, 2}, {16, SHIFT, 3}, {17, SHIFT, 4}, },
			{{-1, ERROR, 22}, {14, SHIFT, 1}, {15, SHIFT, 2}, {16, SHIFT, 3}, {17, SHIFT, 4}, },
			{{-1, ERROR, 23}, {14, SHIFT, 1}, {15, SHIFT, 2}, {16, SHIFT, 3}, {17, SHIFT, 4}, },
			{{-1, ERROR, 24}, {14, SHIFT, 1}, {15, SHIFT, 2}, {16, SHIFT, 3}, {17, SHIFT, 4}, },
			{{-1, ERROR, 25}, {21, SHIFT, 40}, },
			{{-1, ERROR, 26}, {17, SHIFT, 41}, {18, SHIFT, 42}, },
			{{-1, ERROR, 27}, {13, SHIFT, 43}, },
			{{-1, REDUCE, 2}, {2, SHIFT, 15}, {3, SHIFT, 16}, {4, SHIFT, 17}, {5, SHIFT, 18}, {6, SHIFT, 19}, {7, SHIFT, 20}, },
			{{-1, REDUCE, 3}, {2, SHIFT, 15}, {3, SHIFT, 16}, {4, SHIFT, 17}, {5, SHIFT, 18}, {6, SHIFT, 19}, {7, SHIFT, 20}, },
			{{-1, REDUCE, 5}, {8, SHIFT, 21}, {9, SHIFT, 22}, },
			{{-1, REDUCE, 6}, {8, SHIFT, 21}, {9, SHIFT, 22}, },
			{{-1, REDUCE, 7}, {8, SHIFT, 21}, {9, SHIFT, 22}, },
			{{-1, REDUCE, 8}, {8, SHIFT, 21}, {9, SHIFT, 22}, },
			{{-1, REDUCE, 9}, {8, SHIFT, 21}, {9, SHIFT, 22}, },
			{{-1, REDUCE, 10}, {8, SHIFT, 21}, {9, SHIFT, 22}, },
			{{-1, REDUCE, 12}, {10, SHIFT, 23}, {11, SHIFT, 24}, },
			{{-1, REDUCE, 13}, {10, SHIFT, 23}, {11, SHIFT, 24}, },
			{{-1, REDUCE, 15}, },
			{{-1, REDUCE, 16}, },
			{{-1, REDUCE, 20}, },
			{{-1, REDUCE, 21}, },
			{{-1, ERROR, 42}, {19, SHIFT, 44}, },
			{{-1, REDUCE, 17}, },
			{{-1, REDUCE, 23}, {20, SHIFT, 46}, },
			{{-1, ERROR, 45}, {21, SHIFT, 47}, },
			{{-1, ERROR, 46}, {19, SHIFT, 44}, },
			{{-1, REDUCE, 22}, },
			{{-1, REDUCE, 24}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 5}, },
			{{-1, 6}, },
			{{-1, 7}, {13, 28}, {14, 29}, },
			{{-1, 8}, {15, 30}, {16, 31}, {17, 32}, {18, 33}, {19, 34}, {20, 35}, },
			{{-1, 9}, {21, 36}, {22, 37}, },
			{{-1, 10}, {23, 38}, {24, 39}, },
			{{-1, 27}, },
			{{-1, 45}, {46, 48}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: '$', iconst, dconst, function key name",
			"expecting: '{'",
			"expecting: '&&', '||', '<', '<=', '>', '>=', '==', '!=', '+', '-', '*', '/', EOF",
			"expecting: '('",
			"expecting: EOF",
			"expecting: '&&', '||', EOF",
			"expecting: '&&', '||', '<', '<=', '>', '>=', '==', '!=', EOF",
			"expecting: '&&', '||', '<', '<=', '>', '>=', '==', '!=', '+', '-', EOF",
			"expecting: name",
			"expecting: '$'",
			"expecting: '}'",
			"expecting: function key name, '{'",
			"expecting: ')'",
			"expecting: ',', '}'",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 2, 3, 4, 5, 6, 7, 2, 2, 8, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 11, 12, 6, 6, 7, 7, 7, 7, 7, 7, 2, 2, 2, 2, 2, 12, 8, 2, 13, 10, 8, 12, 10, 
        };*/
}
