/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.formula.sablecc.parser;

import fr.umlv.symphonie.formula.sablecc.node.*;
import fr.umlv.symphonie.formula.sablecc.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    public void caseTAnd(TAnd node)
    {
        index = 0;
    }

    public void caseTOr(TOr node)
    {
        index = 1;
    }

    public void caseTLt(TLt node)
    {
        index = 2;
    }

    public void caseTLteq(TLteq node)
    {
        index = 3;
    }

    public void caseTGt(TGt node)
    {
        index = 4;
    }

    public void caseTGteq(TGteq node)
    {
        index = 5;
    }

    public void caseTEqual(TEqual node)
    {
        index = 6;
    }

    public void caseTNeq(TNeq node)
    {
        index = 7;
    }

    public void caseTPlus(TPlus node)
    {
        index = 8;
    }

    public void caseTMinus(TMinus node)
    {
        index = 9;
    }

    public void caseTMult(TMult node)
    {
        index = 10;
    }

    public void caseTDiv(TDiv node)
    {
        index = 11;
    }

    public void caseTLPar(TLPar node)
    {
        index = 12;
    }

    public void caseTRPar(TRPar node)
    {
        index = 13;
    }

    public void caseTDollar(TDollar node)
    {
        index = 14;
    }

    public void caseTIconst(TIconst node)
    {
        index = 15;
    }

    public void caseTDconst(TDconst node)
    {
        index = 16;
    }

    public void caseTFunctionKeyName(TFunctionKeyName node)
    {
        index = 17;
    }

    public void caseTLBrace(TLBrace node)
    {
        index = 18;
    }

    public void caseTName(TName node)
    {
        index = 19;
    }

    public void caseTComma(TComma node)
    {
        index = 20;
    }

    public void caseTRBrace(TRBrace node)
    {
        index = 21;
    }

    public void caseEOF(EOF node)
    {
        index = 22;
    }
}
