/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.formula.sablecc.node;

import java.util.*;
import fr.umlv.symphonie.formula.sablecc.analysis.*;

public final class ADivExprHighPriority extends PExprHighPriority
{
    private PExprHighPriority _exprHighPriority_;
    private TDiv _div_;
    private PExpratom _expratom_;

    public ADivExprHighPriority()
    {
    }

    public ADivExprHighPriority(
        PExprHighPriority _exprHighPriority_,
        TDiv _div_,
        PExpratom _expratom_)
    {
        setExprHighPriority(_exprHighPriority_);

        setDiv(_div_);

        setExpratom(_expratom_);

    }
    public Object clone()
    {
        return new ADivExprHighPriority(
            (PExprHighPriority) cloneNode(_exprHighPriority_),
            (TDiv) cloneNode(_div_),
            (PExpratom) cloneNode(_expratom_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivExprHighPriority(this);
    }

    public PExprHighPriority getExprHighPriority()
    {
        return _exprHighPriority_;
    }

    public void setExprHighPriority(PExprHighPriority node)
    {
        if(_exprHighPriority_ != null)
        {
            _exprHighPriority_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprHighPriority_ = node;
    }

    public TDiv getDiv()
    {
        return _div_;
    }

    public void setDiv(TDiv node)
    {
        if(_div_ != null)
        {
            _div_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _div_ = node;
    }

    public PExpratom getExpratom()
    {
        return _expratom_;
    }

    public void setExpratom(PExpratom node)
    {
        if(_expratom_ != null)
        {
            _expratom_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expratom_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_exprHighPriority_)
            + toString(_div_)
            + toString(_expratom_);
    }

    void removeChild(Node child)
    {
        if(_exprHighPriority_ == child)
        {
            _exprHighPriority_ = null;
            return;
        }

        if(_div_ == child)
        {
            _div_ = null;
            return;
        }

        if(_expratom_ == child)
        {
            _expratom_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_exprHighPriority_ == oldChild)
        {
            setExprHighPriority((PExprHighPriority) newChild);
            return;
        }

        if(_div_ == oldChild)
        {
            setDiv((TDiv) newChild);
            return;
        }

        if(_expratom_ == oldChild)
        {
            setExpratom((PExpratom) newChild);
            return;
        }

    }
}
