/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.formula.sablecc.node;

import java.util.*;
import fr.umlv.symphonie.formula.sablecc.analysis.*;

public final class AExpratomExprHighPriority extends PExprHighPriority
{
    private PExpratom _expratom_;

    public AExpratomExprHighPriority()
    {
    }

    public AExpratomExprHighPriority(
        PExpratom _expratom_)
    {
        setExpratom(_expratom_);

    }
    public Object clone()
    {
        return new AExpratomExprHighPriority(
            (PExpratom) cloneNode(_expratom_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpratomExprHighPriority(this);
    }

    public PExpratom getExpratom()
    {
        return _expratom_;
    }

    public void setExpratom(PExpratom node)
    {
        if(_expratom_ != null)
        {
            _expratom_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expratom_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_expratom_);
    }

    void removeChild(Node child)
    {
        if(_expratom_ == child)
        {
            _expratom_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_expratom_ == oldChild)
        {
            setExpratom((PExpratom) newChild);
            return;
        }

    }
}
