/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.formula.sablecc.node;

import java.util.*;
import fr.umlv.symphonie.formula.sablecc.analysis.*;

public final class AIconstExpratom extends PExpratom
{
    private TIconst _iconst_;

    public AIconstExpratom()
    {
    }

    public AIconstExpratom(
        TIconst _iconst_)
    {
        setIconst(_iconst_);

    }
    public Object clone()
    {
        return new AIconstExpratom(
            (TIconst) cloneNode(_iconst_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIconstExpratom(this);
    }

    public TIconst getIconst()
    {
        return _iconst_;
    }

    public void setIconst(TIconst node)
    {
        if(_iconst_ != null)
        {
            _iconst_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _iconst_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_iconst_);
    }

    void removeChild(Node child)
    {
        if(_iconst_ == child)
        {
            _iconst_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_iconst_ == oldChild)
        {
            setIconst((TIconst) newChild);
            return;
        }

    }
}
