/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.formula.sablecc.node;

import java.util.*;
import fr.umlv.symphonie.formula.sablecc.analysis.*;

public final class ALowPriorityExpr extends PExpr
{
    private PExprLowPriority _exprLowPriority_;

    public ALowPriorityExpr()
    {
    }

    public ALowPriorityExpr(
        PExprLowPriority _exprLowPriority_)
    {
        setExprLowPriority(_exprLowPriority_);

    }
    public Object clone()
    {
        return new ALowPriorityExpr(
            (PExprLowPriority) cloneNode(_exprLowPriority_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALowPriorityExpr(this);
    }

    public PExprLowPriority getExprLowPriority()
    {
        return _exprLowPriority_;
    }

    public void setExprLowPriority(PExprLowPriority node)
    {
        if(_exprLowPriority_ != null)
        {
            _exprLowPriority_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprLowPriority_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_exprLowPriority_);
    }

    void removeChild(Node child)
    {
        if(_exprLowPriority_ == child)
        {
            _exprLowPriority_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_exprLowPriority_ == oldChild)
        {
            setExprLowPriority((PExprLowPriority) newChild);
            return;
        }

    }
}
