/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.formula.sablecc.node;

import java.util.*;
import fr.umlv.symphonie.formula.sablecc.analysis.*;

public final class AMinusExprNormalPriority extends PExprNormalPriority
{
    private PExprNormalPriority _exprNormalPriority_;
    private TMinus _minus_;
    private PExprHighPriority _exprHighPriority_;

    public AMinusExprNormalPriority()
    {
    }

    public AMinusExprNormalPriority(
        PExprNormalPriority _exprNormalPriority_,
        TMinus _minus_,
        PExprHighPriority _exprHighPriority_)
    {
        setExprNormalPriority(_exprNormalPriority_);

        setMinus(_minus_);

        setExprHighPriority(_exprHighPriority_);

    }
    public Object clone()
    {
        return new AMinusExprNormalPriority(
            (PExprNormalPriority) cloneNode(_exprNormalPriority_),
            (TMinus) cloneNode(_minus_),
            (PExprHighPriority) cloneNode(_exprHighPriority_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMinusExprNormalPriority(this);
    }

    public PExprNormalPriority getExprNormalPriority()
    {
        return _exprNormalPriority_;
    }

    public void setExprNormalPriority(PExprNormalPriority node)
    {
        if(_exprNormalPriority_ != null)
        {
            _exprNormalPriority_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprNormalPriority_ = node;
    }

    public TMinus getMinus()
    {
        return _minus_;
    }

    public void setMinus(TMinus node)
    {
        if(_minus_ != null)
        {
            _minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _minus_ = node;
    }

    public PExprHighPriority getExprHighPriority()
    {
        return _exprHighPriority_;
    }

    public void setExprHighPriority(PExprHighPriority node)
    {
        if(_exprHighPriority_ != null)
        {
            _exprHighPriority_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprHighPriority_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_exprNormalPriority_)
            + toString(_minus_)
            + toString(_exprHighPriority_);
    }

    void removeChild(Node child)
    {
        if(_exprNormalPriority_ == child)
        {
            _exprNormalPriority_ = null;
            return;
        }

        if(_minus_ == child)
        {
            _minus_ = null;
            return;
        }

        if(_exprHighPriority_ == child)
        {
            _exprHighPriority_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_exprNormalPriority_ == oldChild)
        {
            setExprNormalPriority((PExprNormalPriority) newChild);
            return;
        }

        if(_minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(_exprHighPriority_ == oldChild)
        {
            setExprHighPriority((PExprHighPriority) newChild);
            return;
        }

    }
}
