/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.formula.sablecc.node;

import java.util.*;
import fr.umlv.symphonie.formula.sablecc.analysis.*;

public final class AMultExprHighPriority extends PExprHighPriority
{
    private PExprHighPriority _exprHighPriority_;
    private TMult _mult_;
    private PExpratom _expratom_;

    public AMultExprHighPriority()
    {
    }

    public AMultExprHighPriority(
        PExprHighPriority _exprHighPriority_,
        TMult _mult_,
        PExpratom _expratom_)
    {
        setExprHighPriority(_exprHighPriority_);

        setMult(_mult_);

        setExpratom(_expratom_);

    }
    public Object clone()
    {
        return new AMultExprHighPriority(
            (PExprHighPriority) cloneNode(_exprHighPriority_),
            (TMult) cloneNode(_mult_),
            (PExpratom) cloneNode(_expratom_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultExprHighPriority(this);
    }

    public PExprHighPriority getExprHighPriority()
    {
        return _exprHighPriority_;
    }

    public void setExprHighPriority(PExprHighPriority node)
    {
        if(_exprHighPriority_ != null)
        {
            _exprHighPriority_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprHighPriority_ = node;
    }

    public TMult getMult()
    {
        return _mult_;
    }

    public void setMult(TMult node)
    {
        if(_mult_ != null)
        {
            _mult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _mult_ = node;
    }

    public PExpratom getExpratom()
    {
        return _expratom_;
    }

    public void setExpratom(PExpratom node)
    {
        if(_expratom_ != null)
        {
            _expratom_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expratom_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_exprHighPriority_)
            + toString(_mult_)
            + toString(_expratom_);
    }

    void removeChild(Node child)
    {
        if(_exprHighPriority_ == child)
        {
            _exprHighPriority_ = null;
            return;
        }

        if(_mult_ == child)
        {
            _mult_ = null;
            return;
        }

        if(_expratom_ == child)
        {
            _expratom_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_exprHighPriority_ == oldChild)
        {
            setExprHighPriority((PExprHighPriority) newChild);
            return;
        }

        if(_mult_ == oldChild)
        {
            setMult((TMult) newChild);
            return;
        }

        if(_expratom_ == oldChild)
        {
            setExpratom((PExpratom) newChild);
            return;
        }

    }
}
