/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.formula.sablecc.node;

import java.util.*;
import fr.umlv.symphonie.formula.sablecc.analysis.*;

public final class APlusExprNormalPriority extends PExprNormalPriority
{
    private PExprNormalPriority _exprNormalPriority_;
    private TPlus _plus_;
    private PExprHighPriority _exprHighPriority_;

    public APlusExprNormalPriority()
    {
    }

    public APlusExprNormalPriority(
        PExprNormalPriority _exprNormalPriority_,
        TPlus _plus_,
        PExprHighPriority _exprHighPriority_)
    {
        setExprNormalPriority(_exprNormalPriority_);

        setPlus(_plus_);

        setExprHighPriority(_exprHighPriority_);

    }
    public Object clone()
    {
        return new APlusExprNormalPriority(
            (PExprNormalPriority) cloneNode(_exprNormalPriority_),
            (TPlus) cloneNode(_plus_),
            (PExprHighPriority) cloneNode(_exprHighPriority_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlusExprNormalPriority(this);
    }

    public PExprNormalPriority getExprNormalPriority()
    {
        return _exprNormalPriority_;
    }

    public void setExprNormalPriority(PExprNormalPriority node)
    {
        if(_exprNormalPriority_ != null)
        {
            _exprNormalPriority_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprNormalPriority_ = node;
    }

    public TPlus getPlus()
    {
        return _plus_;
    }

    public void setPlus(TPlus node)
    {
        if(_plus_ != null)
        {
            _plus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _plus_ = node;
    }

    public PExprHighPriority getExprHighPriority()
    {
        return _exprHighPriority_;
    }

    public void setExprHighPriority(PExprHighPriority node)
    {
        if(_exprHighPriority_ != null)
        {
            _exprHighPriority_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprHighPriority_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_exprNormalPriority_)
            + toString(_plus_)
            + toString(_exprHighPriority_);
    }

    void removeChild(Node child)
    {
        if(_exprNormalPriority_ == child)
        {
            _exprNormalPriority_ = null;
            return;
        }

        if(_plus_ == child)
        {
            _plus_ = null;
            return;
        }

        if(_exprHighPriority_ == child)
        {
            _exprHighPriority_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_exprNormalPriority_ == oldChild)
        {
            setExprNormalPriority((PExprNormalPriority) newChild);
            return;
        }

        if(_plus_ == oldChild)
        {
            setPlus((TPlus) newChild);
            return;
        }

        if(_exprHighPriority_ == oldChild)
        {
            setExprHighPriority((PExprHighPriority) newChild);
            return;
        }

    }
}
