/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.formula.sablecc.node;

import fr.umlv.symphonie.formula.sablecc.analysis.*;

public final class Start extends Node
{
    private PFormule _pFormule_;
    private EOF _eof_;

    public Start()
    {
    }

    public Start(
        PFormule _pFormule_,
        EOF _eof_)
    {
        setPFormule(_pFormule_);
        setEOF(_eof_);
    }

    public Object clone()
    {
        return new Start(
            (PFormule) cloneNode(_pFormule_),
            (EOF) cloneNode(_eof_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseStart(this);
    }

    public PFormule getPFormule()
    {
        return _pFormule_;
    }

    public void setPFormule(PFormule node)
    {
        if(_pFormule_ != null)
        {
            _pFormule_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pFormule_ = node;
    }

    public EOF getEOF()
    {
        return _eof_;
    }

    public void setEOF(EOF node)
    {
        if(_eof_ != null)
        {
            _eof_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _eof_ = node;
    }

    void removeChild(Node child)
    {
        if(_pFormule_ == child)
        {
            _pFormule_ = null;
            return;
        }

        if(_eof_ == child)
        {
            _eof_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_pFormule_ == oldChild)
        {
            setPFormule((PFormule) newChild);
            return;
        }

        if(_eof_ == oldChild)
        {
            setEOF((EOF) newChild);
            return;
        }
    }

    public String toString()
    {
        return "" +
            toString(_pFormule_) +
            toString(_eof_);
    }
}
