/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.formula.sablecc.node;

import fr.umlv.symphonie.formula.sablecc.analysis.*;

public final class TDconst extends Token
{
    public TDconst(String text)
    {
        setText(text);
    }

    public TDconst(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TDconst(getText(), getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDconst(this);
    }
}
