/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.formula.sablecc.node;

import fr.umlv.symphonie.formula.sablecc.analysis.*;

public final class TFunctionKeyName extends Token
{
    public TFunctionKeyName(String text)
    {
        setText(text);
    }

    public TFunctionKeyName(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TFunctionKeyName(getText(), getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFunctionKeyName(this);
    }
}
